### ISSUE TITLE
Possible wrong button width

### ISSUE THREAD

**Issue by filipopo** [SourceEnginePlayground/Hyperborea#1]
https://github.com/SourceEnginePlayground/Hyperborea/blob/7ea438cfee8a1e5acad34f1ae6f3a4a3feabe934/sp/src/game/gameui2/panel_options.cpp#L191

Pardon me if i didn't get it but.. isnt this supposed to be
`ButtonApply->SetPos(X0 + ButtonApply->GetWide(), ContentY1 - ButtonApply->GetTall());`
instead of
`ButtonApply->SetPos(X0 + ButtonDone->GetWide(), ContentY1 - ButtonApply->GetTall());`

**Comment by filipopo** [comment]
I also noticed that there appear to be un-needed includes in files like
https://github.com/SourceEnginePlayground/Hyperborea/blob/7ea438cfee8a1e5acad34f1ae6f3a4a3feabe934/sp/src/game/gameui2/basepanel.cpp#L14
basepanel.cpp includes basepanel.h which already inclludes vgui/ISurface.h
I'm not aware of why you would include it twice, i mean it doesn't really matter i suppose but it's neater without them

**Comment by NicolasDe** [comment]
1. nope
2. not sure why I left it there
